//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPANTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARTICIPANTES()
        {
            this.VAUCHERS = new HashSet<VAUCHERS>();
        }
    
        public int ID_PARTICIPANTE { get; set; }
        public int DNI { get; set; }
        public string APELLIDO { get; set; }
        public string NOMBRE { get; set; }
        public string EMAIL { get; set; }
        public string DIRECCION { get; set; }
        public string CIUDAD { get; set; }
        public int CODIGO_POSTAL { get; set; }
        public bool ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VAUCHERS> VAUCHERS { get; set; }
    }
}
