//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAUCHERS
    {
        public int ID_VAUCHER { get; set; }
        public string CODIGO { get; set; }
        public int PARTICIPANTE { get; set; }
        public byte PRODUCTO { get; set; }
        public bool ESTADO { get; set; }
        public System.DateTime FECHA_INGRESO { get; set; }
    
        public virtual PARTICIPANTES PARTICIPANTES { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
